networks:
  beacon-dev:
    external: true
  supabase-local:
    external: true

services:
  app:
    container_name: beacon-phoenix
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app
      - vscode-extension:/root/.vscode-server-insiders
    command: sleep infinity
    networks:
      - beacon-dev
      - supabase-local

volumes:
  vscode-extension: